#!/usr/bin/env bash
# Κατεβάζει τις 139 εικόνες που φιλοξενούνται στη Wikimedia.
# Τρέξε το ΜΕΣΑ στον φάκελο assets/questions_pics :
#     bash download_images.sh
set -u
UA="MindClimber/1.0 (educational quiz game; contact: you@example.com)"
ok=0; fail=0
download() {
  if [ -s "$1" ]; then echo "  ήδη υπάρχει: $1"; ok=$((ok+1)); return; fi
  if curl -fsSL -A "$UA" --retry 3 --retry-delay 2 -o "$1" "$2"; then
    echo "  ✓ $1"; ok=$((ok+1))
  else echo "  ✗ ΑΠΕΤΥΧΕ: $1"; rm -f "$1"; fail=$((fail+1)); fi
  sleep 0.3
}

download "place_kastro_oyindsor.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Windsor_Castle_at_Sunset_-_Nov_2006.jpg?width=650"
download "place_kolossaio_romi.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Colosseum.jpg?width=650"
download "place_pyrgos_tis_pizas.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Leaning_Tower_of_Pisa.jpg?width=650"
download "place_kokkini_plateia_moscha.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Red_Square.jpg?width=650"
download "place_sfigga_tis_gkizas.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Great_Sphinx_of_Giza.jpg?width=650"
download "place_loyvro_parisi.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Louvre_Museum_Wikimedia_Commons.jpg?width=650"
download "place_palati_toy_mpakigcham_londino.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Buckingham_Palace.jpg?width=650"
download "flag_india.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sari_2.jpg?width=650"
download "place_gefyra_toy_limanioy_toy_sidnei.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sydney_Harbour_Bridge.jpg?width=650"
download "place_big_ben_londino.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Big_Ben.jpg?width=650"
download "place_pyrgos_toy_aifel_parisi.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Eiffel_Tower.jpg?width=650"
download "space_selini.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/FullMoon2010.jpg?width=650"
download "place_empire_state_building_nea_yorki.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Empire_State_Building.jpg?width=650"
download "place_gefyra_karoloy_praga.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Charles_Bridge.jpg?width=650"
download "place_palati_toy_potsdam.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sanssouci_Palace.jpg?width=650"
download "place_pyrgos_toy_tokyo.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/TokyoTower.jpg?width=650"
download "portrait_laskarina_mpoympoylina.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Bouboulina.JPG?width=650"
download "animal_koala.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Koala_climbing_tree.jpg?width=650"
download "place_grand_canyon_ipa.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Grand_Canyon.jpg?width=650"
download "place_panagia_ton_parision.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Notre-Dame_de_Paris.jpg?width=650"
download "place_katarraktes_angkel_venezoyela.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Angel_falls.jpg?width=650"
download "place_kappadokia_toyrkia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Cappadocia_Balloon_Inflating_Wikimedia_Commons.JPG?width=650"
download "animal_kamilopardali.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Giraffa_camelopardalis_reticulata.jpg?width=650"
download "place_naos_karnak.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Karnak_Temple.jpg?width=650"
download "place_limni_vaikali.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Lake_Baikal.jpg?width=650"
download "place_oros_foytzi_iaponia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Fuji_from_Lake_Kawaguchi.jpg?width=650"
download "place_vasiliki_sacre_cur_parisi.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sacre_coeur_paris.jpg?width=650"
download "animal_tigris.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Tiger.50.jpg?width=650"
download "place_christos_lytrotis_rio.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Christ_the_Redeemer.jpg?width=650"
download "space_aris.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/OSIRIS_Mars_true_color.jpg?width=650"
download "place_delta_toy_okavangko.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Okavango_Delta.jpg?width=650"
download "place_tower_bridge_londino.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Tower_Bridge.jpg?width=650"
download "space_gi.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/The_Earth_seen_from_Apollo_17.jpg?width=650"
download "place_akropoli_athinon.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Acropolis_of_Athens.jpg?width=650"
download "space_afroditi.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Venus-real_color.jpg?width=650"
download "animal_liontari.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Lion_waiting_in_Namibia.jpg?width=650"
download "place_taipei_101.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Taipei_101.JPG?width=650"
download "animal_delfini.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Dolphin.jpg?width=650"
download "place_oros_kilimantzaro.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Kilimanjaro_from_Amboseli.jpg?width=650"
download "place_atomioym_vryxelles.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Atomium_.jpg?width=650"
download "place_opera_tis_viennis.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Vienna_State_Opera.jpg?width=650"
download "place_sachara_erimos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sahara_desert.jpg?width=650"
download "portrait_ioannis_kapodistrias.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Ioannis_Kapodistrias_(1776-1831).jpg?width=650"
download "animal_pigkoyinos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Penguin2.jpg?width=650"
download "place_sintrivani_trevi_romi.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Trevi_Fountain.jpg?width=650"
download "place_opera_toy_sidnei.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sydney_Opera_House.jpg?width=650"
download "place_burj_khalifa_ntoympai.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Burj_Khalifa_Night_View_04.jpg?width=650"
download "place_fiord_tis_norvigias.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Geirangerfjord_from_Flydalsjuvet.jpg?width=650"
download "place_one_world_trade_center_nea_yorki.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/One_World_Trade_Center.jpg?width=650"
download "place_siniko_teichos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Great_Wall_of_China.jpg?width=650"
download "space_kronos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Saturn_during_Equinox.jpg?width=650"
download "animal_kagkoyro.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Kangaroo_and_joey03.jpg?width=650"
download "place_pyramides_tis_gkizas.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Pyramids_of_Giza.jpg?width=650"
download "portrait_theodoros_kolokotronis.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Theodoros_Kolokotronis_(1882).jpg?width=650"
download "place_taz_machal_india.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Taj_Mahal.jpg?width=650"
download "place_katarraktes_niagara.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Niagara_Falls.jpg?width=650"
download "place_cn_tower_toronto.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/CN_Tower.jpg?width=650"
download "place_gefyra_mproyklin_nea_yorki.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Brooklyn_Bridge.jpg?width=650"
download "animal_zevra.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Zebra_Botswana_edit02.jpg?width=650"
download "place_taims_skoyer_nea_yorki.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Times_Square.jpg?width=650"
download "place_plateia_agioy_markoy_venetia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Piazza_San_Marco_Venice.jpg?width=650"
download "space_ilios.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/The%20Sun%20by%20the%20Atmospheric%20Imaging%20Assembly%20of%20NASA%27s%20Solar%20Dynamics%20Observatory%20-%2020100819.jpg?width=650"
download "place_nekra_thalassa.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Dead_Sea_by_David_Shankbone.jpg?width=650"
download "space_dias.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Jupiter.jpg?width=650"
download "place_agalma_tis_eleytherias_nea_yorki.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Statue_of_Liberty.jpg?width=650"
download "place_kathedrikos_agioy_markoy_venetia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/St_Mark%27s_Basilica.jpg?width=650"
download "flag_ellada.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Evzone.jpg?width=650"
download "place_sagrada_familia_varkeloni.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sagrada_Familia_.jpg?width=650"
download "animal_elefantas.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Elephant.jpg?width=650"
download "place_matsoy_pitsoy_peroy.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Machu_Picchu.jpg?width=650"
download "flag_ispania.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Black_and_red_flamenco_dress_with_orange_fan.jpg?width=650"
download "animal_chimpatzis.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Chimpanzees.jpg?width=650"
download "space_poseidonas.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Neptune_Full.jpg?width=650"
download "space_ermis.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Mercury_in_true_color.jpg?width=650"
download "place_kathedrikos_tis_kolonias.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Cologne_Cathedral.jpg?width=650"
download "animal_karcharias.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Great_white_shark_south_africa.jpg?width=650"
download "portrait_georgios_karaiskakis.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Georgios_Karaiskakis.jpg?width=650"
download "place_kastro_toy_oyindsor.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Windsor_Castle_at_night.jpg?width=650"
download "place_stooynchentz_agglia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Stonehenge.jpg?width=650"
download "place_petra_iordania.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Petra_Jordan.jpg?width=650"
download "place_odogefyra_toy_migio_gallia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Creissels%20et%20Viaduct%20de%20Millau.jpg?width=650"
download "place_gennisi_tis_afroditis.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Botticelli_Venus.jpg?width=650"
download "place_westminster_abbey.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Westminster_Abbey.JPG?width=650"
download "place_duomo_di_milano.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Duomo_di_Milano.jpg?width=650"
download "animal_kamila.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Camel.jpg?width=650"
download "place_asteri_tis_nychtas.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/VanGogh-starry_night.jpg?width=650"
download "place_space_needle_siatl.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Space_Needle.jpg?width=650"
download "place_i_kraygi.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/The_Scream.jpg?width=650"
download "place_kastro_toy_edimvoyrgoy.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Edinburgh_Castle_from_the_North.JPG?width=650"
download "place_falaina_fysitiras.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sperm_whale.jpg?width=650"
download "place_palati_ton_versallion.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Palace_of_Versailles.jpg?width=650"
download "place_o_mystikos_deipnos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Leonardo_da_Vinci_(1452-1519)_-_The_Last_Supper_(1495-1498).jpg?width=650"
download "place_apagoreymeni_poli_pekino.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Forbidden_City.jpg?width=650"
download "place_kastro_noisvanstain_germania.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Neuschwanstein_Castle.jpg?width=650"
download "place_tigris_tis_veggalis.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Bengal_tiger.jpg?width=650"
download "place_alkatraz_san_fransisko.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Alcatraz_Island.jpg?width=650"
download "place_i_dimioyrgia_toy_adam.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Creaci%C3%B3n_de_Ad%C3%A1n.jpg?width=650"
download "place_tsitsen_itsa_mexiko.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Chichen_Itza_3.jpg?width=650"
download "place_oros_rasmor_ipa.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Mount_Rushmore.jpg?width=650"
download "place_mporompoyntoyr_indonisia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Borobudur_Temple.jpg?width=650"
download "place_iliotropia_toy_van_gkogk.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Vincent_van_Gogh_-_Sunflowers_(1888%2C_National_Gallery_London).jpg?width=650"
download "place_angkor_vat_kampotzi.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Angkor_Wat.jpg?width=650"
download "animal_gorilas.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Male_silverback_Gorilla.JPG?width=650"
download "place_katarraktes_viktoria.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Victoria_Falls.jpg?width=650"
download "space_oyranos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Uranus2.jpg?width=650"
download "place_naos_toy_oyranoy_pekino.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Temple_of_Heaven.jpg?width=650"
download "portrait_rigas_feraios.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Rigas_Feraios_by_Hess.jpg?width=650"
download "portrait_andreas_miaoylis.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Andreas_Miaoulis.jpg?width=650"
download "costume_skotia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Highlander-kilt.jpg?width=650"
download "animal_poliki_arkoyda.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Polar_Bear_-_Alaska.jpg?width=650"
download "place_moyseio_gkoygkenchaim_mpilmpao.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Museo_Guggenheim_%28Bilbao%29.jpg?width=650"
download "place_pantheon_romi.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Pantheon%2C_Rome.jpg?width=650"
download "portrait_athanasios_diakos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Athanasios_Diakos.JPG?width=650"
download "place_gefyra_rialto_venetia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Rialto_Bridge.jpg?width=650"
download "place_mont_saint_michel_gallia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Mont_Saint-Michel.jpg?width=650"
download "portrait_markos_mpotsaris.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Markos_Botsaris.jpg?width=650"
download "place_i_mona_liza.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Mona_Lisa.jpg?width=650"
download "place_flatiron_building_nea_yorki.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Flatiron_Building.jpg?width=650"
download "place_palati_senmproyn_vienni.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Sch%C3%B6nbrunn_Palace%2C_Vienna.JPG?width=650"
download "place_kamilopardali.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Giraffe_standing.jpg?width=650"
download "place_panta.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Giant_Panda_eating_Bamboo.JPG?width=650"
download "place_kremlino_moscha.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Kremlin.jpg?width=650"
download "place_ponte_vecchio_florentia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Ponte_Vecchio_%28Firenze%29.JPG?width=650"
download "place_chrysler_building_nea_yorki.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Chrysler_Building.jpg?width=650"
download "portrait_odysseas_androytsos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Odysseas-androutsos.jpg?width=650"
download "portrait_konstantinos_kanaris.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Konstantinos_Kanaris.jpg?width=650"
download "place_nisi_toy_pascha.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Moai_Rano_raraku.jpg?width=650"
download "place_palati_toy_dogi_venetia.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Doge%27s_Palace.jpg?width=650"
download "animal_drakos_toy_komonto.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Komodo_dragon_(Varanus_komodoensis).jpg?width=650"
download "place_kastro_tis_pragas.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Prague_Castle.jpg?width=650"
download "space_ploytonas.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Pluto-01_Stern_03_Pluto_Color_TXT.jpg?width=650"
download "place_parthenonas_ti_nychta.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Parthenon_at_night.jpg?width=650"
download "place_avoy_simpel_aigyptos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Abu_Simbel_Temple.jpg?width=650"
download "place_palati_toy_alampra_ispania.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Alhambra_Granada.jpg?width=650"
download "place_moyseio_prado_madriti.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Museo_del_Prado.jpg?width=650"
download "animal_ornithorygchos.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Platypus.jpg?width=650"
download "place_willis_tower_sikago.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Willis_Tower.jpg?width=650"
download "place_katarraktes_igkoyasoy.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/Iguazu_Falls.jpg?width=650"
download "place_moyseio_vretanias.jpg" "https://commons.wikimedia.org/wiki/Special:FilePath/British_Museum_Exterior.jpg?width=650"

echo
echo "Ολοκληρώθηκε: $ok επιτυχίες, $fail αποτυχίες."
if [ "$fail" -gt 0 ]; then echo "Οι ερωτήσεις με αποτυχημένη εικόνα θα πέσουν αυτόματα πίσω στο online link."; fi
